CREATE VIEW ESTADO_DE_CUENTAS

AS

SELECT DISTINCT   dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, SUM(dbo.FACTURAS.VALOR_FACTURA) AS MONTO,

SUM(dbo.CHEQUES.VALOR_CHEQUE) AS PAGOS,  SUM(dbo.FACTURAS.VALOR_FACTURA + dbo.CHEQUES.VALOR_CHEQUE) AS BALANCE FROM dbo.PROVEEDORES INNER JOIN         dbo.FACTURAS ON dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO AND dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO INNER JOIN

                      dbo.CHEQUES ON dbo.FACTURAS.NUMERO_FACTURA = dbo.CHEQUES.NUMERO_FACTURA

GROUP BY dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, dbo.FACTURAS.VALOR_FACTURA, dbo.CHEQUES.VALOR_CHEQUE

GO