create database SCXP

use SCXP

CREATE TABLE PROVEEDORES
(
CODIGO varchar(7) PRIMARY KEY,
NOMBRE varchar(25) not null,
APELLIDO varchar (25) not null,
DIRECCION varchar(35) null,
CIUDAD  varchar (25) null,
TELEFONO varchar (13) null,
)
CREATE TABLE FACTURAS
(
NUMERO_FACTURA INT PRIMARY KEY,
CODIGO VARCHAR(50) NOT NULL,
VALOR_FACTURA MONEY NULL,
FECHA_FACTURA  DATETIME NULL,
FECHA_VENCIMIENTO DATETIME NULL
)

--RELACION FACTURAS CON PROVEEDORES


ALTER TABLE FACTURAS  ADD CONSTRAINT FACTPROV1 FOREIGN

KEY (CODIGO) REFERENCES PROVEEDORES (CODIGO)

ON UPDATE CASCADE

ON DELETE CASCADE

GO


--TABLA CHEQUE

CREATE TABLE CHEQUES
(
NUMERO_CHEQUE INT PRIMARY KEY,
NUMERO_FACTURA INT NOT NULL,
VALOR_CHEQUE MONEY NULL,
FECHA_CHEQUE DATETIME NULL
)

--RELACION DE LA TABLA CHEQUES CON LA TABLA FACTURAS

ALTER TABLE CHEQUES ADD CONSTRAINT FOREIGN KEY (NUMERO_FACTURA)
REFERENCES FACTURAS (NUMERO_FACTURA)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

--TABLA USUARIOS

CREATE TABLE USUARIOS
(
USUARIO NVARCHAR(20) PRIMARY KEY,
CLAVE NVARCHAR(15) NULL

)

--INSERTAR USUARIOS

–-INSERTAR LOS DATOS DE LOS USUARIOS

INSERT INTO USUARIOS (USUARIO,CLAVE) VALUES ('FRANK','YOSOY')

INSERT INTO USUARIOS (USUARIO,CLAVE) VALUES ('ANNERYS','GIGI')

INSERT INTO USUARIOS (USUARIO,CLAVE) VALUES ('DARIANNY','DARY')

INSERT INTO USUARIOS (USUARIO,CLAVE) VALUES ('CAROLINA','CARO')

INSERT INTO USUARIOS (USUARIO,CLAVE) VALUES ('YANNERYS','RUBIA')
SELECT * FROM USUARIOS


CREATE VIEW ESTADO_DE_CUENTAS

AS

SELECT DISTINCT   dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, SUM(dbo.FACTURAS.VALOR_FACTURA) AS MONTO,

SUM(dbo.CHEQUES.VALOR_CHEQUE) AS PAGOS,  SUM(dbo.FACTURAS.VALOR_FACTURA – dbo.CHEQUES.VALOR_CHEQUE) AS BALANCE FROM dbo.PROVEEDORES INNER JOIN         dbo.FACTURAS ON dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO AND dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO INNER JOIN

                      dbo.CHEQUES ON dbo.FACTURAS.NUMERO_FACTURA = dbo.CHEQUES.NUMERO_FACTURA

GROUP BY dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, dbo.FACTURAS.VALOR_FACTURA, dbo.CHEQUES.VALOR_CHEQUE

GO