CREATE DATABASE ISAAC
GO
USE ISAAC

--CREAR TABLAS PROVEEDORES
GO
CREATE TABLE PROVEEDORES
(
CODIGO VARCHAR(7)PRIMARY KEY,
NOMBRES VARCHAR(25)NOT NULL,
APELLIDOS VARCHAR(25)NOT NULL,
DIRECCION VARCHAR(35),
CIUDAD VARCHAR(25),
TELEFONO VARCHAR(13)
)
--CREATE TABLE FACTURA
GO
CREATE TABLE FACTURAS
(
NUMERO_FACTURA INT PRIMARY KEY,
CODIGO VARCHAR(7) NOT NULL,
VALOR_FACTURA MONEY NULL,
FECHA_FACTURA DATETIME NULL,
FECHA_VENCIMIENTO DATETIME NULL

)
GO
---CREAR TABLA RECIBOS

CREATE TABLE CHEQUES
(
NUMERO_CHEQUE INT PRIMARY KEY NOT NULL,
NUMERO_FACTURA INT NOT NULL,
VALOR_CHEQUE MONEY NULL,
FECHA_CHEQUE DATETIME NULL

) 
GO
CREATE TABLE USUARIOS
(
USUARIO NVARCHAR(20) PRIMARY KEY,
CLAVE NVARCHAR(15) NOT NULL
)
	GO
 --CREAR LAS RELACIONES ENTRE TABLAS
 ALTER TABLE FACTURAS ADD CONSTRAINT RELACION_FACTURAS_PROVEEDORES FOREIGN KEY (CODIGO) --CLAVE FOREANEA
 REFERENCES PROVEEDORES (CODIGO)
 GO
 --RELACION ENTRE FACTURAS Y CHEQUES
  ALTER TABLE CHEQUES ADD CONSTRAINT RELACION_CHEQUES_FACTURAS FOREIGN KEY (NUMERO_FACTURA)
 REFERENCES FACTURAS (NUMERO_FACTURA)
 
 --SE RELACIONA LA TABLA CHEQUES Y FACTURAS COMO CLAVE FOREANA EN NUMERO_FACTURA 
 --CHQ_FACT O CUALQUIER OTRO NOMBRE ES EL NOMBRE ASIGNADO A LA RELACION
 GO
 CREATE VIEW ESTADO_DE_CUENTAS
 
 
 AS
  SELECT DISTINCT 	


                         dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, SUM(dbo.FACTURAS.VALOR_FACTURA) AS MONTO, 
                         SUM(dbo.CHEQUES.VALOR_CHEQUE) AS PAGOS, SUM(dbo.FACTURAS.VALOR_FACTURA + dbo.CHEQUES.VALOR_CHEQUE) AS BALANCE, 
                         dbo.FACTURAS.NUMERO_FACTURA
FROM            dbo.PROVEEDORES INNER JOIN
                         dbo.FACTURAS ON dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO AND dbo.PROVEEDORES.CODIGO = dbo.FACTURAS.CODIGO INNER JOIN
                         dbo.CHEQUES ON dbo.FACTURAS.NUMERO_FACTURA = dbo.CHEQUES.NUMERO_FACTURA
GROUP BY dbo.PROVEEDORES.CODIGO, dbo.PROVEEDORES.NOMBRES, dbo.PROVEEDORES.APELLIDOS, dbo.FACTURAS.VALOR_FACTURA, dbo.CHEQUES.VALOR_CHEQUE, 
                         dbo.FACTURAS.NUMERO_FACTURA

						 GO


						 INSERT INTO USUARIOS VALUES ('ISAAC','MARRERO')
						 INSERT INTO USUARIOS VALUES ('FRANK','REYES')